name: teebow1e - Build LaTeX CV
on: [push]
jobs:
  build_cv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      pages: write
      id-token: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
      - name: Rename CV file
        run: mv cv.pdf TrungTQT_CV_EN.pdf

      - name: Install pdf2htmlEX
        run: |
          sudo apt update
          sudo apt install -y libfontconfig1 libcairo2 libjpeg-turbo8
          sudo apt --fix-broken install
          wget https://github.com/pdf2htmlEX/pdf2htmlEX/releases/download/v0.18.8.rc1/pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-bionic-x86_64.deb
          sudo mv pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-bionic-x86_64.deb pdf2htmlEX.deb
          sudo dpkg -i ./pdf2htmlEX.deb

      - name: Convert PDF to HTML
        run: pdf2htmlEX --process-outline 1 --fallback 1 --bg-format svg --zoom 1.3 --process-type3 1 --dest-dir out TrungTQT_CV_EN.pdf
      
      # (Optional) Create release
      - name: Generate release tag
        id: tag
        run: |
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh
          sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
          echo "release_tag=CV_Build_EN_$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ./TrungTQT_CV_EN.pdf

permissions:
  contents: write
  pages: write
  id-token: write
